### ISSUE TITLE
Issue with alembic revisions

### ISSUE THREAD

**Issue by EdinH** [bitnami/bitnami-docker-airflow-worker#10]
After I set up the DB backend and initially run the bitnami docker-compose it works fine, but after I restart they are popping out this issue. It tries to upgrade, but in the database, its alembic_version has two revisions. It works fine when I run it locally on my machine and this pops out on Kubernetes.

```
bitnami    INFO  Initializing airflow-worker
airflow INFO  ==> No injected configuration files found. Creating default config file...
Error executing 'postInstallation': INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/alembic/script/base.py", line 162, in _catch_revision_errors
    yield
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/alembic/script/base.py", line 364, in _upgrade_revs
    revs = list(revs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/alembic/script/revision.py", line 811, in _iterate_revisions
    total_space = set(
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/alembic/script/revision.py", line 813, in <genexpr>
    ).intersection(
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/alembic/script/revision.py", line 741, in _iterate_related_revisions
    raise RevisionError(
alembic.script.revision.RevisionError: Requested revision 1507a7289a2f overlaps with other requested revisions 13eb55f81627

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/commands/db_command.py", line 31, in initdb
    db.initdb()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/db.py", line 549, in initdb
    upgradedb()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/db.py", line 688, in upgradedb
    command.upgrade(config, 'heads')
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/migrations/env.py", line 108, in <module>
    run_migrations_online()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/migrations/env.py", line 102, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/alembic/runtime/migration.py", line 511, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/alembic/command.py", line 287, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/alembic/script/base.py", line 365, in _upgrade_revs
    return [
  File "/opt/bitnami/python/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/alembic/script/base.py", line 196, in _catch_revision_errors
    compat.raise_from_cause(util.CommandError(err.args[0]))
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/alembic/util/compat.py", line 308, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/alembic/util/compat.py", line 301, in reraise
    raise value.with_traceback(tb)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/alembic/script/base.py", line 162, in _catch_revision_errors
    yield
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/alembic/script/base.py", line 364, in _upgrade_revs
    revs = list(revs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/alembic/script/revision.py", line 811, in _iterate_revisions
    total_space = set(
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/alembic/script/revision.py", line 813, in <genexpr>
    ).intersection(
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/alembic/script/revision.py", line 741, in _iterate_related_revisions
    raise RevisionError(
alembic.util.exc.CommandError: Requested revision 1507a7289a2f overlaps with other requested revisions 13eb55f81627
```

**Comment by miguelaeh** [comment]
Hi @EdinH ,
The `alembic_version` should have only one row. It seems that by some reason you ended up with two.
To fix the issue you will need to delete one of them like the following:

```
delete from alembic_version where version_num='<version_you_want_to_remove>';
```

**Comment by EdinH** [comment]
Hi @miguelaeh. Thanks for your reply. I have tried that, but it recreates every time I restart the scheduler or worker.

**Comment by miguelaeh** [comment]
Hi @EdinH ,
Could you share how did you deploy the application so we can reproduce the issue? Our tests involve the docker-compose restarts and we are not facing this issue in our batteries.

**Comment by EdinH** [comment]
Hi @miguelaeh, 
Sorry for being late with the reply. 
The docker images (airflow/Dockerfile, airflow-scheduler/Dockerfile, airflow-worker/Dockerfile) are built, tagged, and pushed to Amazon ECR in the mentioned order (airflow, scheduler, worker) to be finally deployed to Amazon EKS. The necessary env variables are stored in configmaps.

**Comment by miguelaeh** [comment]
Hi @EdinH ,
I mean the parameters passed to the Helm Chart or the env variables in case you are using docker-compose.
Are you using https://github.com/bitnami/charts/tree/master/bitnami/airflow ?

**Comment by EdinH** [comment]
Hi @miguelaeh. No, I am using https://github.com/bitnami/bitnami-docker-airflow

**Comment by miguelaeh** [comment]
Could you share the env vars you are using in your configmap?

**Comment by EdinH** [comment]
Hi @miguelaeh. 
airflowscheduler map is used for both scheduler  and worker

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: airflowscheduler
  namespace: dev
data:
    AIRFLOW__CELERY__BROKER_URL: redis://redis:redispass@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ************************
    AIRFLOW_CONN_AWS_S3: *************************
    AWS_ACCESS_KEY_ID: *******************
    AWS_SECRET_ACCESS_KEY: ***************
    BUCKET_NAME: raw-data
    REGION: eu-west-1
    BUCKET_KEY: raw/batches.vcf.gz
    PLINK19: /opt/bitnami/airflow/tmp_data/tools/plink19
    PLINK20: /opt/bitnami/airflow/tmp_data/tools/plink20
    APT_FORMAT_RESULT: /opt/bitnami/airflow/tmp_data/tools/apt-format-result
    VCF_BATCH: /opt/bitnami/airflow/tmp_data/vcf/batches.vcf.gz
    REF_DATA: /opt/bitnami/airflow/tmp_data/ref/ref_data_v1
    DATA: /opt/bitnami/airflow/tmp_data/vcf/
    RESULTS: /opt/bitnami/airflow/tmp_data/results/ref_batch
    AIRFLOW_DATABASE_NAME: airflow_db
    AIRFLOW_DATABASE_USERNAME: airflow
    AIRFLOW_DATABASE_PASSWORD: airflow
    AIRFLOW_DATABASE_HOST: ************************
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:***********************:5432/airflow_db
    AIRFLOW_USERNAME: user
    AIRFLOW_PASSWORD: *********
    AIRFLOW_WEBSERVER_PORT_NUMBER: '80'
    AIRFLOW_EXECUTOR: CeleryExecutor
    AIRFLOW_LOAD_EXAMPLES: "no"
    AIRFLOW__WEBSERVER__LOG_FETCH_TIMEOUT_SEC: "600"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
    REDIS_PASSWORD: redispass
    REDIS_USER: redis
```

airflow map:

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: airflow
  namespace: dev
data:
    AIRFLOW__CELERY__BROKER_URL: redis://redis:redispass@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ************************
    AIRFLOW__CORE__DAGS_FOLDER: /opt/bitnami/airflow/dags
    AIRFLOW_CONN_AWS_S3: ************************
    AWS_ACCESS_KEY_ID: ************************
    AWS_SECRET_ACCESS_KEY: ************************
    BUCKET_NAME: raw-data
    REGION: eu-west-1
    BUCKET_KEY: raw/batches.vcf.gz
    PLINK19: /opt/bitnami/airflow/tmp_data/tools/plink19
    PLINK20: /opt/bitnami/airflow/tmp_data/tools/plink20
    APT_FORMAT_RESULT: /opt/bitnami/airflow/tmp_data/tools/apt-format-result
    VCF_BATCH: /opt/bitnami/airflow/tmp_data/vcf/batches.vcf.gz
    REF_DATA: /opt/bitnami/airflow/tmp_data/ref/ref_data_v1
    DATA: /opt/bitnami/airflow/tmp_data/vcf/
    RESULTS: /opt/bitnami/airflow/tmp_data/results/ref_batch
    AIRFLOW_DATABASE_NAME: airflow_db
    AIRFLOW_DATABASE_USERNAME: airflow
    AIRFLOW_DATABASE_PASSWORD: airflow
    AIRFLOW_DATABASE_HOST: ************************
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:************************:5432/airflow_db
    AIRFLOW_USERNAME: user
    AIRFLOW_PASSWORD: *********
    AIRFLOW_WEBSERVER_PORT_NUMBER: '8080'
    AIRFLOW_EXECUTOR: CeleryExecutor
    AIRFLOW__WEBSERVER__LOG_FETCH_TIMEOUT_SEC: "600"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
    AIRFLOW_LOAD_EXAMPLES: "yes"
```

**Comment by miguelaeh** [comment]
Hi @EdinH ,
I noticed you are not using the env vars provided in the container but the Airflow env vars directly. It could be causing issues in the `airflow.cfg` file. Please refactor the env vars to match the ones defined here: https://github.com/bitnami/bitnami-docker-airflow/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/airflow-env.sh

For example, you are using `AIRFLOW__CORE__SQL_ALCHEMY_CONN` instead of the env var used by the container logic to set it which is `AIRFLOW_DATABASE_HOST`

**Comment by EdinH** [comment]
Thanks @miguelaeh. I will check that, but I think I will shift to the airflow helm chart as it makes more sense. Come back to you.

**Comment by EdinH** [comment]
Thanks @miguelaeh. It worked, but I realized that using a helm chart is a much better option. So, I will switch to that.
