### ISSUE TITLE
Issues with launching a worker

### ISSUE THREAD

**Issue by claudexie** [bitnami/bitnami-docker-airflow-worker#8]
I have found others also incounter this issue too ：
https://forum.astronomer.io/t/issues-with-launching-a-worker/839

2020-11-17T01:34:33.013837375Z [0m
2020-11-17T01:34:33.013869249Z [0m[1mWelcome to the Bitnami airflow-worker container[0m
2020-11-17T01:34:33.013872939Z [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-airflow-worker[0m
2020-11-17T01:34:33.013876323Z [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-airflow-worker/issues[0m
2020-11-17T01:34:33.013878585Z [0m
2020-11-17T01:34:35.536838388Z nami    INFO  Initializing airflow-worker
2020-11-17T01:34:35.56832703Z airflow INFO  ==> No injected configuration files found. Creating default config file...
2020-11-17T01:34:43.704589576Z airflow INFO  ==> Configuring Airflow database...
2020-11-17T01:34:43.744347834Z airflow INFO  ==> Setting Airflow Fernet key...
2020-11-17T01:34:43.76439701Z airflow INFO  ==> Configuring Airflow Celery Executor...
2020-11-17T01:34:43.775392982Z airflow INFO  ==> Deploying Airflow from scratch...
2020-11-17T01:34:43.777719955Z postgre INFO  Trying to connect to PostgreSQL server
2020-11-17T01:34:43.780868466Z postgre INFO  Found PostgreSQL server listening at xxxxx:5432
2020-11-17T01:34:43.797932479Z postgre INFO  PostgreSQL server listening and working at xxxxx:5432
2020-11-17T01:34:43.803174269Z airflow INFO  ==> Waiting for Airflow Webserver host...
2020-11-17T01:34:43.805699515Z airflow INFO  ==> Waiting for Redis host...
2020-11-17T01:34:43.821162703Z airflow INFO 
2020-11-17T01:34:43.821280047Z airflow INFO  ########################################################################
2020-11-17T01:34:43.821354293Z airflow INFO   Installation parameters for airflow-worker:
2020-11-17T01:34:43.821828793Z airflow INFO     Webserver URL: xxxxx:8080
2020-11-17T01:34:43.821962795Z airflow INFO   This installation requires no credentials.
2020-11-17T01:34:43.822078802Z airflow INFO  ########################################################################
2020-11-17T01:34:43.822198332Z airflow INFO 
2020-11-17T01:34:43.822299902Z nami    INFO  airflow-worker successfully initialized
2020-11-17T01:34:43.841980604Z [0m[38;5;2mINFO [0m ==> Starting airflow-worker... 
2020-11-17T01:34:49.175187688Z Waiting for db...
2020-11-17T01:34:49.186047578Z Database is ready
2020-11-17T01:34:50.187639936Z [0m[38;5;2mINFO [0m ==> Starting airflow...
2020-11-17T01:34:53.687182Z Traceback (most recent call last):
2020-11-17T01:34:53.687195423Z   File "/opt/bitnami/airflow/venv/bin/airflow", line 37, in <module>
2020-11-17T01:34:53.687249752Z     args.func(args)
2020-11-17T01:34:53.687258735Z   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/cli.py", line 75, in wrapper
2020-11-17T01:34:53.68808132Z     return f(*args, **kwargs)
2020-11-17T01:34:53.688087932Z   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/bin/cli.py", line 1089, in worker
2020-11-17T01:34:53.689246962Z     worker = worker.worker(app=celery_app)
2020-11-17T01:34:53.68925351Z   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
2020-11-17T01:34:53.690420299Z     return self.main(*args, **kwargs)
2020-11-17T01:34:53.690429713Z   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/click/core.py", line 781, in main
2020-11-17T01:34:53.690660943Z     with self.make_context(prog_name, args, **extra) as ctx:
2020-11-17T01:34:53.690667684Z   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/click/core.py", line 698, in make_context
2020-11-17T01:34:53.690851748Z     ctx = Context(self, info_name=info_name, parent=parent, **extra)
2020-11-17T01:34:53.690907202Z TypeError: __init__() got an unexpected keyword argument 'app'

- Output of `docker-compose version` (if applicable): latest

**Comment by marcosbc** [comment]
Hi @claudexie, unfortunately I was not able to reproduce this issue using the [`docker-compose.yml` file from the repo](https://github.com/bitnami/bitnami-docker-airflow-worker/blob/master/docker-compose.yml).

Could you share more info on your deployment and how to reproduce this issue?

**Comment by claudexie** [comment]
> Hi @claudexie, unfortunately I was not able to reproduce this issue using the [`docker-compose.yml` file from the repo](https://github.com/bitnami/bitnami-docker-airflow-worker/blob/master/docker-compose.yml).
> 
> Could you share more info on your deployment and how to reproduce this issue?

thank you for reply，I think it is because i reinsatal apache-airflow to 1.10.10,  this issue comes up..
